"""Build a focused, self-contained technology report and the research log."""
from pathlib import Path
import base64
import html
import json
import hashlib
import re
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"outputs"
TABLE=OUT/"tables"
def read(name):return pd.read_csv(TABLE/(name+".csv"))
def pct(x):return f"{100*x:.1f}%"

class Report:
    def __init__(self):self.md=[];self.web=[]
    def heading(self,title,level=2):self.md.append("#"*level+" "+title);self.web.append(f"<h{level}>{html.escape(title)}</h{level}>")
    def inline(self,text):
        text=html.escape(text)
        text=re.sub(r"\*\*(.*?)\*\*",r"<strong>\1</strong>",text)
        text=re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)",r'<a href="\2">\1</a>',text)
        return text
    def para(self,text):self.md.append(text);self.web.append("<p>"+self.inline(text)+"</p>")
    def table(self,d):
        rows=[[str(x).replace("|","/") for x in row] for row in d.itertuples(index=False,name=None)]
        self.md.append("| "+" | ".join(map(str,d.columns))+" |\n| "+" | ".join(["---"]*len(d.columns))+" |\n"+"\n".join("| "+" | ".join(row)+" |" for row in rows))
        self.web.append('<div class="table">'+d.to_html(index=False,escape=True,border=0)+'</div>')
    def bullets(self,items):self.md.append("\n".join("- "+x for x in items));self.web.append("<ul>"+"".join("<li>"+self.inline(x)+"</li>" for x in items)+"</ul>")
    def figure(self,name):
        p=OUT/"figures"/(name+".png")
        self.md.append(f"![{name.replace('_',' ')}](figures/{name}.png)")
        b=base64.b64encode(p.read_bytes()).decode()
        self.web.append(f'<figure><img alt="{html.escape(name)}" src="data:image/png;base64,{b}"></figure>')
    def write(self,name):
        (OUT/(name+".md")).write_text("\n\n".join(self.md)+"\n")
        css="""body{margin:0;color:#263c46;background:#f3f6f7;font-family:Arial,sans-serif;line-height:1.6}main{max-width:1050px;margin:35px auto;padding:48px;background:white}h1{font-size:32px;line-height:1.2}h2{font-size:24px;margin-top:44px;border-top:1px solid #d3dfe3;padding-top:24px}h3{font-size:18px}p,li{font-size:15px}a{color:#17667b}table{width:100%;border-collapse:collapse;font-size:13px}th{text-align:left;background:#e5eff2}th,td{padding:9px 11px;border-bottom:1px solid #d3dfe3}figure{margin:25px 0}img{width:100%;height:auto}.table{overflow-x:auto}footer{font-size:12px;color:#64747e;margin-top:45px}@media(max-width:700px){main{padding:22px;margin:0}h1{font-size:25px}}@media print{body{background:white}main{margin:0;padding:0}figure,table{break-inside:avoid}h2{break-after:avoid}}"""
        doc='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI patent technology extension</title><style>'+css+'</style></head><body><main>'+"\n".join(self.web)+'<footer>Independent exploratory analysis · 4 October 2026 · Original dataset preserved</footer></main></body></html>'
        (OUT/(name+".html")).write_text(doc)

def research_log(summary):
    entries=[]
    def entry(observation,hypothesis,decision,justification,result,limitation,alternatives):
        entries.append(dict(observation=observation,hypothesis=hypothesis,decision=decision,justification=justification,result=result,limitation=limitation,reasonable_alternatives=alternatives))
    entry("The preceding analysis found Qualcomm denominator expansion and NVIDIA ML growth.","Technology composition can distinguish substantive portfolio changes from label-only changes.","Enrich Qualcomm 2021/2023 and NVIDIA 2014–2016/2021–2023 grants.","These directly match the two findings requested for investigation; NVIDIA windows have equal three-year duration.","7,813 supplied grant rows selected; 263,602 source rows outside the extension scope, not deleted from the original analysis.","This extension cannot locate the precise transition year between NVIDIA windows.","Enrich every company/year; use intermediate years; use a probability sample.")
    entry("Official USPTO PatentsView bulk metadata was downloadable.","A census avoids convenience-sample bias.","Download fixed December 2024 release and verify published MD5s; retain all target titles, abstracts and dates.","Public bulk inputs are reproducible and remove the need for random sampling.","All 7,813 target grants have title, abstract and filing-date fields.","Titles/abstracts are not a full reading of claims or specifications.","Stratified random sampling; Google Patents search exports; licensed commercial metadata.")
    entry("CPC is one-to-many and evolves over time.","Reclassification may create apparent technology changes.","Use current codes from one snapshot; retain at-issue codes for sensitivity.","A common snapshot improves comparability without pretending classification history is stable.","Current and at-issue interpretations broadly agree; paired NVIDIA check uses 742 early and 784 recent grants.","At-issue codes absent for 267 early NVIDIA grants; three further grants excluded only from paired sensitivity because current codes absent.","At-issue-only analysis; IPC concordance; historical CPC scheme crosswalk.")
    entry("Communications codes overlap across subclasses.","A simple membership partition can identify where the net non-AI increase lies.","Define communications-associated as any H04W/L/B/J/K/M code; each grant counted once in the partition.","The partition is exact, interpretable and does not sum overlapping subclass totals.","Communications-associated increase 1,608 / total classifier-negative increase 1,617 = 99.4%.","Association with communications is not an exclusive invention field or proof of a causal reason.","First-listed CPC; fractional subclass credit (also supplied); detailed CPC groups.")
    entry("Current CPC omits six reissues.","Code absence is a metadata limitation, not an invalid patent.","Retain reissues, blank codes and a no-communications/no-current-code category.","Deleting unusual identifiers would miscount genuine grants.","No patent rows removed; six missing current-CPC cases exported for review.","A missing code must not be interpreted as absence of that technology.","Exclude reissues with explicit sensitivity; retrieve original-patent codes.")
    entry("Classifier-negative is operational, not biological/technical truth.","Qualcomm composition accounting may depend on the AI cutoff.","Repeat the decomposition at 50, 86 and 93; repeat with inventional codes only.","This probes label and coding choices without selecting a cutoff for significance.","Communications explain 98.6%–99.7% of the net negative-grant increase across 12 specifications.","Threshold sensitivity does not validate AIPD recall or precision.","Human claim-based labels; probabilistic score weighting.")
    entry("Text phrases identify concrete themes but abstracts contain boilerplate.","Specific technical terms, corroborated by CPC and title-only checks, are more useful than raw topic ranks.","Use disclosed regex phrase rules and separate exploratory bigram contrasts; no opaque topic model.","Raw phrase rankings include drafting phrases such as 'various examples', which are not technologies.","Sidelink, learned methods and autonomy increase in both title-only and combined-text analyses.","Rules are exploratory and may miss synonyms or mention background technologies.","NMF/LDA after boilerplate removal; embeddings with manual validation; blinded human coding.")
    entry("Ray-tracing and rendering have orthographic/stem variants.","Exact wording choices can affect counts.","Match ray-tracing/ray tracing/raytracing stems and render*; freeze rules in text_rules.json.","These are reasonable spelling and morphology variants, chosen before the final tables rather than for significance.","Ray-tracing matches 5→60; rendering 118→106; 56 of 60 recent ray-tracing grants are ML86-negative.","A keyword does not prove the patented claim's principal technical contribution.","Exact-phrase counts; manual classification of graphics claims.")
    entry("Qualcomm grant dates are later than the activity described in filings.","Expansion may be driven by prior filing cohorts or prosecution delays.","Add direct filing dates and grant lags; preserve unusual durations.","Timing is needed before attributing 2023 grants to 2023 innovation or strategy.","2,916 / 3,446 negative 2023 grants were filed in 2020–2021; lag median 2.12→2.30 years, mean almost unchanged.","Only granted applications are observed; direct filing dates need not equal first priority.","All pre-grant filings; allowance/prosecution histories; earliest family priorities.")
    entry("NVIDIA ML-positive and non-ML counts both change.","Share growth can reflect more positives and fewer negatives.","Use two-factor Shapley accounting, averaging both update orders.","Contributions add exactly and avoid choosing an arbitrary ordering.",summary["accounting_result"],"Accounting contributions are not causal treatment effects.","One-order counterfactual; log-odds decomposition; Kitagawa decomposition.")
    entry("Neural and vision/control evidence overlap in NVIDIA ML grants.","An additive partition can describe most of the ML rise without double-counting.","Order explicit learning text, then vision/control evidence without such text, then remaining ML grants.","The hierarchy makes the accounting transparent; retain independent overlapping theme counts as well.","Explicit learning category 0→177, vision/control without explicit learning 1→38, other 6→15; total 7→230.","Category order changes attribution; 'vision/control' combines image/vision CPC, perception phrases and autonomous mentions.","Nonexclusive thematic prevalence; fractional multi-theme allocation.")
    entry("G06V recognition classifications were revised with transfers from G06K9.","An isolated G06V trend can confuse scheme change with innovation.","Check a harmonized G06T/G06V/G06K9 union and paired current/issue records.","Official CPC revision notice documents reclassification; text corroboration is independent of code migration.","Paired vision/pattern share increases 29.5%→50.0% current and 28.3%→48.9% at issue.","This is a pragmatic union, not a complete historical CPC concordance.","Detailed revision crosswalk; IPC; exclude G06V and rely on text.")
    entry("The targeted rows are a finite census, selected after the preceding EDA.","Population-style patent-independent p-values or confidence intervals would impose unsupported assumptions.","Use exact finite-cohort effects, threshold/snapshot checks and leave-one-quarter-out ranges; no new confirmatory tests.","Unknown patent families and a one-year Qualcomm cohort make conventional inference unjustified.","Sidelink share change remains +9.68 to +10.67 pp; NVIDIA explicit-learning change +23.11 to +24.45 pp under quarter omission.","Sensitivity ranges are not confidence intervals; these results do not generalize to unobserved inventions.","Family-clustered inference after family linkage; prespecified replication period; temporal bootstrap with validated assumptions.")
    entry("Ten recent NVIDIA grants explicitly mention learned methods but fall below ML86.","Some disagreement reflects component boundaries, text scope or model error.","Export all ten; inspect a linked accelerator case using original patent pages.","Anomalies inform interpretation and should not be deleted or automatically relabeled.","Nine remain any-AI86-positive. Three linked same-title accelerator grants have ML scores 0.000484, 0.999996, 0.003449; all hardware86-positive.","This does not establish a specific classifier error mechanism; claims differ and same-title patents can be distinct.","Expert claims adjudication; full AIPD inference-input audit; broader family study.")
    (OUT/"research_log.jsonl").write_text("\n".join(json.dumps(x,ensure_ascii=False) for x in entries)+"\n")
    text=["# Research log — CPC/text extension"]
    for i,x in enumerate(entries,1):
        text.append(f"## Decision {i}")
        for k,v in x.items():text.append(f"**{k.replace('_',' ').capitalize()}:** {v}")
    (OUT/"research_log.md").write_text("\n\n".join(text)+"\n")

if __name__=="__main__":
    expected="f4fdc65071bfba1448107e9ac63d25d56f0ab996fd3b38ffd2d897dc55beb256"
    if hashlib.sha256((ROOT/"data"/"cohort_frame.csv").read_bytes()).hexdigest()!=expected:
        raise ValueError("Cohort input changed: review the source-specific interpretation before regenerating this report.")
    d=pd.read_csv(ROOT/"data"/"analysis_patent_cohorts.csv.gz",dtype={"doc_id":str},float_precision="round_trip")
    q=d.loc[d.company.eq("Qualcomm")];n=d.loc[d.company.eq("NVIDIA")]
    q0=q.loc[q.cohort.eq("2021")];q1=q.loc[q.cohort.eq("2023")]
    n0=n.loc[n.cohort.eq("2014-2016")];n1=n.loc[n.cohort.eq("2021-2023")]
    neg0=q0.loc[q0.predict86_any_ai.eq(0)];neg1=q1.loc[q1.predict86_any_ai.eq(0)]
    sens=read("qualcomm_growth_sensitivity")
    account=read("share_change_accounting").set_index("company")
    cpc=read("cpc_subclass_counts")
    text=read("text_theme_counts")
    cases=read("illustrative_patents")
    case_manifest=json.loads((ROOT/"data"/"case_study_manifest.json").read_text())
    summary={"qualcomm_net_non_ai_growth":len(neg1)-len(neg0),"qualcomm_communications_growth":int(neg1.cpc_current_communications.sum()-neg0.cpc_current_communications.sum()),"nvidia_net_ml_growth":int(n1.predict86_ml.sum()-n0.predict86_ml.sum()),"nvidia_explicit_learning_ml_growth":int((n1.predict86_ml.eq(1)&n1.text_combined_explicit_learning_or_neural).sum()),"accounting_result":f"Qualcomm: positive-count contribution {account.loc['Qualcomm','positive_count_contribution_pp']:.2f} pp, negative-count contribution {account.loc['Qualcomm','negative_count_contribution_pp']:.2f} pp; NVIDIA: {account.loc['NVIDIA','positive_count_contribution_pp']:.2f} pp and {account.loc['NVIDIA','negative_count_contribution_pp']:.2f} pp."}
    (OUT/"key_findings.json").write_text(json.dumps(summary,indent=2)+"\n")
    r=Report();r.heading("What changed technologically? Qualcomm and NVIDIA",1)
    r.para("**Qualcomm's expanding classifier-negative denominator is overwhelmingly a communications-grant expansion, especially wireless networking and sidelink. NVIDIA's higher ML share is corroborated by explicit neural/learning text, image understanding, autonomous-system perception and selected accelerator inventions.** These are descriptive findings about granted patents in the supplied extract, not estimates of corporate R&D spending or causal strategy changes.")
    r.para("This extension examines Qualcomm's 2,147 grants in 2021 and 3,870 in 2023, plus NVIDIA's 1,010 grants in 2014–2016 and 786 in 2021–2023. Official [USPTO PatentsView metadata](https://zenodo.org/records/15783125), release dated 31 December 2024, supplies titles, abstracts, CPC classifications and direct application filing dates. Classifier-negative means supplied **any-AI86 = 0**; ML means **ML86 = 1**, not verified ground truth.")
    r.heading("Qualcomm: where the extra denominator comes from")
    r.para(f"Classifier-negative grants increase **1,829 → 3,446 (+1,617)**. Grants associated with communications CPC codes increase **1,514 → 3,122 (+1,608)**. Thus **99.4% of the net increase** lies in this category. The complementary category rises only 315 → 324. This is an exact two-way partition: a grant with any H04W, H04L, H04B, H04J, H04K or H04M code enters the communications category once, even when it has additional computing codes.")
    r.figure("01_qualcomm_denominator")
    rows=[]
    for code,label in [("H04W","Wireless networks"),("H04L","Digital information transmission"),("H04B","Transmission"),("G06F","Digital data processing"),("H01L","Semiconductors")]:
        s=cpc[(cpc.company=="Qualcomm")&(cpc.population=="non_ai")&(cpc.snapshot=="current")&(cpc.cpc_subclass==code)].set_index("cohort")
        a=int(s.loc["2021","patents"]) if "2021" in s.index else 0;b=int(s.loc["2023","patents"]) if "2023" in s.index else 0
        rows.append([code,label,f"{a:,}",f"{b:,}",f"{b-a:+,}"])
    r.table(pd.DataFrame(rows,columns=["CPC","Technology","2021 negative grants","2023 negative grants","Change"]))
    r.para("Subclass totals overlap and must not be added. The particularly large H04W increase and almost unchanged G06F count show that the extra denominator is concentrated in wireless communications, rather than a general expansion of conventional computing.")
    r.heading("What the communications patents describe",3)
    r.para("Title and abstract phrases identify **sidelink**, beam/beamforming techniques, uplink/downlink control, channel-state reporting and retransmission mechanisms. Sidelink mentions rise **32 → 415**, from **1.75% to 12.04%** of classifier-negative grants (+10.29 percentage points). Title-only sidelink mentions rise 21 → 355 (+9.15 pp), so the result does not rely on abstract wording alone. These are overlapping technical indicators, not exclusive validated topics.")
    r.figure("02_qualcomm_text")
    r.para("For example, [US11546105B2](https://patents.google.com/patent/US11546105B2/en) concerns selective channel-state reports for a group of devices communicating over sidelink. [US11546031B2](https://patents.google.com/patent/US11546031B2/en) concerns feedback about wide-bandwidth beamforming. Both are classifier-negative at 86 and carry H04W/H04L/H04B codes. Their descriptions fit cellular-radio optimization. However, literal 'new radio/5G' phrase prevalence falls 6.45% → 3.92% under the disclosed rule; the evidence does **not** justify calling every additional communications patent a 5G patent.")
    r.heading("When this activity originated",3)
    r.para("**2,916 of the 3,446 classifier-negative grants in 2023 (84.6%) were directly filed in 2020–2021**; 1,980 were filed in 2021 alone. Of the 415 sidelink mentions, 399 are in those 2020–2021 filing cohorts. Median filing-to-grant lag increases only 2.12 → 2.30 years; the mean is 2.40 → 2.41 years, and the proportion with more than four years of lag falls 8.91% → 4.24%. The expansion is not concentrated in a very old backlog.")
    r.figure("03_qualcomm_filing_timing")
    r.para("The supported mechanism is **a larger volume of communications applications reaching grant, mostly after a roughly two-year lag**. AI86-positive grants also increase 318 → 424 (+33.3%). Their share nevertheless falls 14.81% → 10.96% because negative grants grow much faster. A symmetric count decomposition assigns +3.26 pp to the positive-count change and −7.11 pp to the negative-count change, summing to −3.86 pp. This is arithmetic attribution, not a causal effect. Grant-only data cannot distinguish higher filing volume, different allowance rates, continuation practices or prosecution timing.")
    r.heading("NVIDIA: what accounts for the shift")
    r.para("ML86-labelled grants increase **7 → 230** despite total grants falling **1,010 → 786** across equal-length three-year windows. The ML share rises **0.69% → 29.26% (+28.57 pp)**. Independent text evidence is substantial: explicit neural/machine/deep-learning mentions rise **0 → 187 (23.79% of recent grants)**, with 113 appearing in titles. Of those 187 recent grants, 177 are ML86-positive.")
    r.figure("05_nvidia_ml_partition")
    r.para("An exact ordered partition separates the ML increase into: **177 additional grants with explicit learned-method text**; **37 additional grants with vision/control evidence but no explicit learning phrase** (1 → 38); and **9 additional remaining ML-labelled grants** (6 → 15). The explicit-learning category accounts for **79.4% of the +223 ML grant increase**. Vision/control evidence here means G06T/G06V membership, a disclosed perception/geometry phrase, or an autonomous-system mention; it is not a human-adjudicated invention taxonomy.")
    r.heading("The technologies are vision, learned computation and autonomy",3)
    r.para("Recent NVIDIA grants carry G06N specific-computational-model codes 229 times, compared with zero in the early cohort. Image processing/generation (G06T) rises 299 → 323; image/video recognition (G06V) rises 2 → 162; control/navigation (G05D) rises 0 → 66; and vehicle drive control (B60W) rises 0 → 41. These memberships overlap. **169 of the 230 recent ML grants (73.5%) have image/vision CPC evidence**, while 54 explicitly mention autonomous systems. The evidence points to learned visual perception and image synthesis, with autonomous-vehicle and computing implementation applications.")
    r.figure("04_nvidia_cpc")
    r.para("Concrete examples include [US10922793B2](https://patents.google.com/patent/US10922793B2/en), which generates missing image content using a neural network; [US10997433B2](https://patents.google.com/patent/US10997433B2/en), which uses learned image segmentation to identify driving lanes and boundaries; and [US10997492B2](https://patents.google.com/patent/US10997492B2/en), which concerns conversion to lower-precision formats. These illustrate image synthesis, autonomous perception and efficient numerical computation rather than a generic undifferentiated 'AI' category. They were selected deterministically for visible theme matches, not to estimate theme prevalence.")
    r.heading("Graphics continue alongside learned methods",3)
    r.para("Autonomous-system mentions rise **1 → 93**. Ray-tracing mentions rise **5 → 60**, but **56 of those 60 recent grants are ML86-negative**. Rendering mentions are **118 → 106**, while the share increases 11.7% → 13.5% because the later total is smaller. Digital data-processing CPC prevalence is roughly stable (48.4% → 50.0%). NVIDIA's portfolio therefore combines a substantial increase in learned methods and perception with ongoing graphics and computing activity; the evidence does not support treating all advanced graphics patents as ML.")
    r.figure("06_nvidia_text")
    r.heading("An anomaly that changes how classifier scores should be read")
    anomaly=read("accelerator_classifier_anomaly")
    show=anomaly[["doc_id","ai_score_ml","predict86_ml","predict86_any_ai","predict86_hardware"]].copy()
    show.ai_score_ml=show.ai_score_ml.map(lambda x:f"{x:.6f}")
    show.columns=["Patent","ML score","ML86","Any AI86","Hardware86"]
    r.para("Three linked NVIDIA grants have the same sparse-convolutional-neural-network accelerator title, G06N/G06F codes and hardware86-positive labels, but radically different ML scores:")
    r.table(show)
    r.para("The low-scoring 10891538 and 11847550 records have identical abstracts describing index-vector and coordinate computations; 10997496's abstract explicitly describes computations in a neural-network accelerator. The original [US11847550B2 patent PDF]("+case_manifest["url"]+") confirms a continuation relationship to 10891538 and a continuation-in-part chain involving 10997496. Its earliest listed provisional filing is 11 August 2016. Thus a 2023 grant can extend much older technical activity, and related patents can cross classifier component boundaries. Different claim scope, wording and classifier error remain possible explanations; this example does not establish which explanation is responsible.")
    r.para("Across the recent NVIDIA cohort, ten grants explicitly mention learned methods but are ML86-negative; nine are nevertheless any-AI86-positive. The exception, 11810268, describes neural-network image enhancement and falls below all supplied AI86 component flags. All ten are retained and exported for expert review. Literal text, CPC, broad AI labels and the ML component label measure different things.")
    r.heading("Uncertainty and robustness")
    r.bullets([f"**Threshold and classification choice:** Qualcomm's communications share of net negative-grant growth ranges **{100*sens.communications_fraction_of_net_increase.min():.1f}%–{100*sens.communications_fraction_of_net_increase.max():.1f}%** across 50/86/93 cutoffs, current/at-issue CPC and all/inventional-only code choices.","**CPC reclassification:** the official [2022 CPC notice](https://www.cooperativepatentclassification.org/sites/default/files/cpc/noc/CPCNoticeOfChanges202201/CPCNOC1250RP0760various.pdf) documents transfers involving G06K9 and G06V. A common snapshot plus a G06T/G06V/legacy-G06K9 union reduces this artifact. In paired cases with both snapshots, image/pattern share rises 29.5% → 50.0% using current codes and 28.3% → 48.9% at issue. These checks use 742 early and 784 recent NVIDIA grants; the main analysis retains all 1,796.","**Text drafting:** raw bigram rankings contain boilerplate. Technical phrase rules and title-only checks corroborate the main themes, but are not a validated text classifier.","**Quarter influence:** dropping one grant quarter at a time leaves Qualcomm's sidelink share increase at +9.68 to +10.67 pp, and NVIDIA's explicit-learning increase at +23.11 to +24.45 pp. These are robustness ranges, not confidence intervals.","**Finite-cohort statistics:** reported counts and effects are exact for the specified rows. No new confirmatory p-values or sampling confidence intervals are manufactured: the cohort is a census of these supplied rows, patent families are not globally linked, and the Qualcomm windows supply only four quarters each. Semantic/classification uncertainty is assessed through alternative definitions; it cannot be repaired by a binomial confidence interval."])
    r.heading("Methods and transformations")
    r.para("All analysis is exploratory, including hypotheses motivated by the preceding EDA. No predictive model is fitted because it would add little to composition accounting and risk learning the supplied classifier outputs. Prespecified source/cohort selections, original labels, raw CPC rows, derived memberships, text rules and filing dates are retained. No rows in the 7,813-grant frame are removed from the main analysis. Six reissues lack current CPC and remain in an unknown/no-current-code category. One-to-many CPC memberships are deduplicated only for patent-level counting; fractional subclass credits are also supplied. Every significant decision and reasonable alternative is recorded in research_log.md.")
    r.heading("What would resolve the remaining 'why'")
    r.bullets(["Link patent families and earliest priorities. Recompute counts per family and distinguish new invention activity from continuation or reissue grants.","Add the full population of published applications, including pending/non-granted records, and prosecution histories. Only this can separate a filing-volume wave from allowance or processing changes behind Qualcomm's grant growth.","Review claims in a stratified, blinded sample: NVIDIA low-ML/high-hardware cases and Qualcomm communications cases with/without AI flags. Estimate labeling error with uncertainty from that validation sample.","Extend CPC/text enrichment to intermediate years and all five companies. Use a held-out period or prespecified family-level study for confirmatory comparisons."])
    r.write("technology_report")
    research_log(summary)
    stats=Report();stats.heading("Statistical analysis — finite-cohort composition accounting",1)
    stats.para("All analyses are exploratory. The estimands are descriptive counts, proportions and net-count attributions for the selected source rows, not population or causal effects. No significance tests or fitted prediction models are necessary for these exact accounting questions.")
    s=account.reset_index()[["company","share_change_pp","positive_count_contribution_pp","negative_count_contribution_pp"]].copy()
    for col in s.columns[1:]:s[col]=s[col].map(lambda x:f"{x:+.3f}")
    stats.table(s)
    stats.para("Let s(P,N)=P/(P+N). The positive-count contribution is one-half of [s(P1,N0)−s(P0,N0)] plus [s(P1,N1)−s(P0,N1)]; the negative-count contribution averages the two corresponding negative-count updates. Their sum equals the observed share change. This is Shapley accounting, not a causal model.")
    stats.table(read("leave_one_quarter_out").round(3))
    stats.para("No sampling confidence interval applies to the known count of these supplied grants. A confidence interval for a repeatable patent-generation process would require an explicit sampling/process model, independent or adequately clustered families, and enough temporal units. Those conditions are not established. The sensitivity ranges above do not have 95% coverage and are not labeled confidence intervals. Initial-analysis statistical results are separate; no new confirmatory test is claimed here.")
    stats.write("statistical_analysis")
    quality=Report();quality.heading("CPC/text field quality and provenance",1)
    quality.para("This document records provenance and limitations of the CPC, title, abstract and filing-date fields added for the technology analysis.")
    quality.para("All six bulk ZIP files match the release's published MD5 and byte counts. Title, abstract and direct filing-date fields are nonempty for all 7,813 selected grants. Current CPC is present for 7,807; the six exceptions are genuine reissues and are retained. At-issue CPC is unavailable for 267 early NVIDIA grants, so its comparative sensitivity uses paired records rather than treating absence as a technology zero.")
    quality.table(read("patents_without_current_cpc"))
    quality.para("No negative, unparseable or greater-than-30-year grant lags occur in the Qualcomm negative-grant timing cohort. Source rows, raw CPC records and original classifier values remain available. Missing current CPC is not filled with inferred codes, and text/classifier disagreements are not relabeled.")
    quality.write("cpc_text_quality")
    print("Focused report, statistical note, field-quality note and research log written.")